version: "3.8"
services: 
    backend:
        build: 
            context: ./backend
        volumes: 
            - ./backend:/app
        ports: 
            - 8000:8000
        working_dir: /app
        tty: true
        environment: 
            STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    
    front:
        build: 
            context: ./front
        volumes: 
            - ./front:/app
        ports: 
            - 3000:3000
        working_dir: /app
        tty: true
        environment: 
            NEXT_PUBLIC_STRIPE_KEY: ${NEXT_PUBLIC_STRIPE_KEY}