version: "3.8"
services: 
    app:
        build: .
        volumes: 
            - ./:/app
        ports: 
            - 8000:8000
        working_dir: /app
        tty: true
        environment: 
            STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}